# Generated by Django 5.0.4 on 2024-05-27 04:30

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guardPhone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KR'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KR', unique=True),
        ),
    ]
