# Generated by Django 5.0.4 on 2024-05-27 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_guardphone_alter_user_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guardPhone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^01[0-9]{8,9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^01[0-9]{8,9}$')]),
        ),
    ]
