# Generated by Django 5.0.4 on 2024-06-17 07:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_is_admin_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userBirth', models.DateField(blank=True, null=True)),
                ('userGender', models.CharField(blank=True, max_length=30, null=True)),
                ('guardPhone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^01[0-9]{8,9}$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='guardPhone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userBirth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userGender',
        ),
    ]
