# Generated by Django 5.0.4 on 2024-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userextra_remove_user_guardphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='userGender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
    ]
