# Generated by Django 5.0.4 on 2024-06-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userextra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userextra',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
