# Generated by Django 5.0.4 on 2024-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userextra_height_userextra_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
