# Generated by Django 5.0.4 on 2024-06-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userextra_height_alter_userextra_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
