# Generated by Django 5.0.4 on 2024-06-21 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userextra_height_alter_userextra_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='hospitalCall',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid call number', regex='^01[0-9]{8,9}$')]),
        ),
    ]
