# Generated by Django 5.0.4 on 2024-06-21 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userextra_hospitalcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('postal_code', models.CharField(max_length=10, verbose_name='우편번호')),
                ('city', models.CharField(max_length=100, verbose_name='시/도')),
                ('district', models.CharField(max_length=100, verbose_name='시/군/구')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='동/읍/면')),
                ('road_address', models.CharField(max_length=255, verbose_name='도로명 주소')),
                ('building_number', models.CharField(max_length=20, verbose_name='건물번호')),
                ('detailed_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='상세주소')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
