# Generated by Django 5.0.4 on 2024-06-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='updated_at',
        ),
    ]
