# Generated by Django 5.0.4 on 2024-06-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_useraddress_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='건물번호'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='시/도'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='시/군/구'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='동/읍/면'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='road_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='도로명 주소'),
        ),
    ]
