# Generated by Django 5.0.4 on 2024-06-22 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_useraddress_building_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='hospitalCall',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid call number', regex='^0[0-9]{8,10}$')]),
        ),
    ]
