# Generated by Django 5.0.4 on 2024-06-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_userextra_hospitalcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='우편번호'),
        ),
    ]
