# Generated by Django 5.0.4 on 2024-06-21 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HEAD', '머리'), ('UPPER_BODY', '상체'), ('LOWER_BODY', '하체'), ('HAND_FOOT', '손/발')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hand_foot_symptoms', models.ManyToManyField(blank=True, related_name='hand_foot_symptoms', to='symptom.symptom')),
                ('head_symptoms', models.ManyToManyField(blank=True, related_name='head_symptoms', to='symptom.symptom')),
                ('lower_body_symptoms', models.ManyToManyField(blank=True, related_name='lower_body_symptoms', to='symptom.symptom')),
                ('upper_body_symptoms', models.ManyToManyField(blank=True, related_name='upper_body_symptoms', to='symptom.symptom')),
            ],
        ),
        migrations.AddField(
            model_name='symptom',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom.symptomcategory'),
        ),
    ]
