# Generated by Django 5.0.4 on 2024-06-18 11:51

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_alter_userextra_height_alter_userextra_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pastDisease', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '고혈압'), (2, '심장 질환'), (3, '당뇨'), (4, '알레르기'), (5, '결핵'), (6, '간염')], max_length=30, null=True)),
                ('currentDisease', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '고혈압'), (2, '심장 질환'), (3, '당뇨'), (4, '알레르기'), (5, '결핵'), (6, '간염')], max_length=30, null=True)),
                ('surgicalHistory', models.BooleanField(default=False)),
            ],
        ),
    ]
