# Generated by Django 5.0.4 on 2024-06-18 11:58

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_rename_surgicalhistory_disease_hassurgicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='currentDisease',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '고혈압'), (2, '심장 질환'), (3, '당뇨'), (4, '알레르기'), (5, '결핵'), (6, '간염'), (7, '기타'), (8, '없음')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pastDisease',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '고혈압'), (2, '심장 질환'), (3, '당뇨'), (4, '알레르기'), (5, '결핵'), (6, '간염'), (7, '기타'), (8, '없음')], max_length=30, null=True),
        ),
    ]
