# Generated by Django 5.0.4 on 2024-06-18 15:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_alter_disease_currentdisease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='currentDisease',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HYPERTENSION', '고혈압'), ('HEART_DISEASE', '심장 질환'), ('DIABETES', '당뇨'), ('ALLERGY', '알레르기'), ('TUBERCULOSIS', '결핵'), ('HEPATITIS', '간염'), ('OTHERS', '기타'), ('NONE', '없음')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pastDisease',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HYPERTENSION', '고혈압'), ('HEART_DISEASE', '심장 질환'), ('DIABETES', '당뇨'), ('ALLERGY', '알레르기'), ('TUBERCULOSIS', '결핵'), ('HEPATITIS', '간염'), ('OTHERS', '기타'), ('NONE', '없음')], max_length=30, null=True),
        ),
    ]
