# Generated by Django 5.0.4 on 2024-06-19 02:16

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySymtom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symtomDate', models.DateField()),
                ('symtomHead', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '압박감'), (2, '눈 부위 통증'), (3, '턱 및 얼굴 통증'), (4, '귀 통증'), (5, '급성 두통'), (6, '만성 두통'), (7, '기타')], max_length=100, null=True)),
                ('symtomUpperBody', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '가슴 통증'), (2, '복통'), (3, '소화불량'), (4, '기타 ')], max_length=100, null=True)),
                ('symtomLowerBody', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '허벅지 통증'), (2, '기타')], max_length=100, null=True)),
                ('symtomHandFoot', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '손/발 저림'), (2, '기타')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
