# Generated by Django 5.0.4 on 2024-06-19 02:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symtom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysymtom',
            name='symtomHandFoot',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('numbness', '손/발 저림'), ('other', '기타')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailysymtom',
            name='symtomHead',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pressure', '압박감'), ('eye', '눈 부위 통증'), ('chinFace', '턱 및 얼굴 통증'), ('ear', '귀 통증'), ('acuteHeadache', '급성 두통'), ('chronicHeadache', '만성 두통'), ('other', '기타')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailysymtom',
            name='symtomLowerBody',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('thigh', '허벅지 통증'), ('other', '기타')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailysymtom',
            name='symtomUpperBody',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('chest', '가슴 통증'), ('stomach', '복통'), ('indigestion', '소화불량'), ('other', '기타 ')], max_length=100, null=True),
        ),
    ]
