# Generated by Django 5.0.4 on 2024-06-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symtom', '0002_alter_dailysymtom_symtomhandfoot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysymtom',
            name='symtomDate',
            field=models.DateField(null=True),
        ),
    ]
