# Generated by Django 5.0.4 on 2024-06-22 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='reservationTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='reservationDate',
            field=models.DateField(),
        ),
    ]
