# Generated by Django 5.0.4 on 2024-06-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_remove_meal_id_alter_meal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='mealTime1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealTime2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealTime3',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
