# Generated by Django 5.0.4 on 2024-06-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_meal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='mealAlarmCnt',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
