# Generated by Django 5.0.4 on 2024-06-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_alter_meal_mealalarmcnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='mealAlarmCnt',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=3),
        ),
    ]
