# Generated by Django 5.0.4 on 2024-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_alter_meal_mealalarmcnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='mealTime4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='mealTime5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealAlarmCnt',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
    ]
